/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package expensereport;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author denis
 */


public class AddingNewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddingNewEmployee
     */
    public AddingNewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TechExp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FoodExp = new javax.swing.JTextField();
        TransExp = new javax.swing.JTextField();
        AddedNew = new javax.swing.JButton();
        CancelAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel2.setText("New Employee");

        FirstName.setToolTipText("Enter First Name");

        jLabel3.setText("Tech Expense:");

        TechExp.setToolTipText("Enter Tech Expense");

        jLabel4.setText("Food Expense:");
        jLabel4.setToolTipText("");

        FoodExp.setToolTipText("Enter Food Expense");

        TransExp.setToolTipText("Enter Transportation Expense");

        AddedNew.setText("Add Employee");
        AddedNew.setToolTipText("");
        AddedNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddedNewActionPerformed(evt);
            }
        });

        CancelAdd.setText("Cancel");
        CancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Transportation Expense:");

        jLabel6.setText("Last Name:");

        LastName.setToolTipText("Enter Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FoodExp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddedNew)
                                .addGap(71, 71, 71)
                                .addComponent(CancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TransExp))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TechExp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(LastName)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TechExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FoodExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TransExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddedNew)
                    .addComponent(CancelAdd))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddedNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddedNewActionPerformed
        //Sets up a connection to the database
         String JDBC_DRIVER="com.mysql.jdbc.Driver";
        String DB_URL = "jdbc:mysql://localhost:3306/expensereports";
        String USER= "root";
        String PASS= "";

      
       //Retrieves the results from the textbox the user inputted
        String First = FirstName.getText();
        String Last = LastName.getText();
        String Tech = TechExp.getText();
        String Food = FoodExp.getText();
        String Trans = TransExp.getText();
       
      
        Statement stmt = null;
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
          Connection conn=DriverManager.getConnection(DB_URL,USER,PASS);
            stmt = conn.createStatement();
            //Inserts the values into the Database table to expensereports
            
             
           
             stmt.executeUpdate("INSERT INTO expensereports(UserId, FirstName,LastName) VALUES  (DEFAULT, '"+First+"','"+Last+"')",stmt.RETURN_GENERATED_KEYS);
             ResultSet rs = stmt.getGeneratedKeys();
             int key = 0; 
             if(rs.next()){ key = rs.getInt(1);}
             //Receives the current time and inputs it into the time String
             DateFormat dateTimeInstance = SimpleDateFormat.getDateTimeInstance();
          String time = " ";
           time = time + dateTimeInstance.format(Calendar.getInstance().getTime());
           time = time + ".";
           //Second sql which inserts the persons employee Id, their userId which is the key that connects it to the expense reports table
           //Also inserts the first expense record along with the time stamp of when it was created 
              String sql2 = "INSERT INTO employeesexpenses(EmployeeID,UserId,TechExp, FoodExp, TransExp, TimeStamp) VALUES( DEFAULT, '"+key+"',  '"+Tech+"', '"+Food+"', '"+Trans+"','"+time+"')";
            stmt.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null,"Created Successfully!");
        }
     
    catch(Exception e)
    {  JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
        }
//After the addition has been made, the window is removed and the user
//is sent back to the main menu
   
   this.dispose();
    
      MainMenu back = new MainMenu();
      back.setVisible(true);
       
    }//GEN-LAST:event_AddedNewActionPerformed

    private void CancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAddActionPerformed
        //If the user presses the cancel button the user is returned to the main menu
        MainMenu x = new MainMenu();
        x.setVisible(true);
       
        this.dispose();
        
       
    }//GEN-LAST:event_CancelAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingNewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddedNew;
    private javax.swing.JButton CancelAdd;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField FoodExp;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField TechExp;
    private javax.swing.JTextField TransExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
